<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'org\\bovigo\\vfs\\' => array($vendorDir . '/mikey179/vfsStream/src/main/php'),
    'XML_Util' => array($vendorDir . '/pear/xml_util'),
    'Twig_' => array($vendorDir . '/twig/twig/lib'),
    'StupidHttp_' => array($vendorDir . '/bolt80/stupidhttp/lib'),
    'Structures' => array($vendorDir . '/pear/structures_graph'),
    'Prophecy\\' => array($vendorDir . '/phpspec/prophecy/src'),
    'PieCrust' => array($baseDir . '/src', $baseDir . '/tests/src'),
    'PEAR' => array($vendorDir . '/pear/pear_exception'),
    'Netcarver\\Textile' => array($vendorDir . '/netcarver/textile/src'),
    'Mustache' => array($vendorDir . '/mustache/mustache/src'),
    'Michelf' => array($vendorDir . '/michelf/php-markdown', $vendorDir . '/michelf/php-smartypants'),
    'Log' => array($vendorDir . '/pear', $vendorDir . '/pear/log'),
    'Console' => array($vendorDir . '/pear', $vendorDir . '/pear/console_commandline', $vendorDir . '/pear/console_getopt'),
    'Benchmark_' => array($vendorDir . '/pear'),
    'Archive_Tar' => array($vendorDir . '/pear/archive_tar'),
);
